apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dotnet-

resources:
- ../../../base-dotnet
- route.yaml

commonLabels:
  app: front-end-service

configMapGenerator:
- name: service-config
  files: 
  - config/appSettings.json

patchesJson6902:
- path: patch_deployment.yaml
  target:
    kind: Deployment
    name: service
- path: patch_service.yaml
  target:
    kind: Service
    name: service 

images:
- name: default-container
  newName: image-registry.openshift-image-registry.svc:5000/workspace/front-end-service
  newTag: latest