apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dotnet-

resources:
- ../../../base-dotnet

commonLabels:
  app: back-end-service

patchesJson6902:
- path: patch_deployment.yaml
  target:
    kind: Deployment
    name: service
- path: patch_service.yaml
  target:
    kind: Service
    name: service 

images:
- name: default-container
  newName: image-registry.openshift-image-registry.svc:5000/workspace/back-end-service
  newTag: latest